name: BDD Runner
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to pull feature files, install TypeDB, and execute the tests
    steps:
    - uses: actions/checkout@v2

    - name: Install Julia
      run: |
        mkdir ~/Downloads
        cd ~/Downloads
        wget https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.2-linux-x86_64.tar.gz
        tar -xvzf julia-1.6.2-linux-x86_64.tar.gz
        sudo cp -r julia-1.6.2 /opt/
        sudo ln -s /opt/julia-1.6.2/bin/julia /usr/local/bin/julia
        julia

    - name: Run TypeDB Server
      run: |
        typedb server &
    - name: Pulling our feature files
      run: |
        ls -a
        mkdir features
        cd features 
        git clone https://github.com/Humans-of-Julia/TypeDBClient.jl.git
        ls
    - id: foo
      uses: Humans-of-Julia/TypeDBRunner@0.1.3
      with:
        who-to-greet: 'Mark Schulzee'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash