name: BDD Runner
on: [push]

jobs:
  TypeDBClient:
    runs-on: ubuntu-latest
    name: BDD Runner TypeDBClient.jl jobs
    steps:
      - uses: actions/checkout@v2
        with:
          path: 

      - name: Pulling our feature files
        run: |
          mkdir ~/features
          cd ~/features 
          git clone https://github.com/Humans-of-Julia/TypeDBClient.jl.git
          ls
          cd TypeDBClient.jl
          ls  
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6.2'
          arch: 'x64'
          show-versioninfo: 'true'
      - name: Install TypeDBClient.jl & Behavior
        run: |
          julia -e 'println("Hello, World!")'
          julia -e 'using Pkg; Pkg.add(url="https://github.com/Humans-of-Julia/TypeDBClient.jl.git")'
          julia -e 'using Pkg; Pkg.add("Behavior")'
        shell: bash          
      - name: Start BDD Runner
        run: |
          julia -e 'println(pwd())'
          julia -e 'cd("/home/runner/work/TypeDBClient.jl/TypeDBClient.jl")'
          julia -e 'println(pwd())'
          julia -e 'println(readdir())'
          julia -e 'cd("/home/runner/work/TypeDBClient.jl/TypeDBClient.jl/test")'
          julia -e 'println(pwd())'
          julia -e 'println(readdir("/home/runner/work/TypeDBClient.jl/TypeDBClient.jl/test"))'
          julia -e '/home/runner/work/TypeDBClient.jl/TypeDBClient.jl/test/runner.jl'
        shell: bash
      - name: Show a random number
        run: echo random-number 20
        shell: bash