name: BDD Runner
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to pull feature files, install TypeDB, and execute the tests
    steps:
      - uses: actions/checkout@v2
      - name: Run TypeDB Server
        run: |
          typedb server &
      - name: Pulling our feature files
        run: |
          mkdir ~/features
          cd ~/features 
          git clone https://github.com/Humans-of-Julia/TypeDBClient.jl.git
          ls
          cd TypeDBClient.jl
          ls  
      - name: Show a random number
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash